# Configure persistent volume claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backend-pvc
  namespace: default
spec:
  storageClassName: "cloud"
  accessModes:
    -   ReadWriteOnce
  resources:
    requests:
      storage: 5Gi