# Role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bdm-default-yoda
subjects:
- kind: ServiceAccount
  name: zoda
  namespace: default
  apiGroup: ""
roleRef:
  kind: Role
  name: adm-default
  apiGroup: ""