# Provision storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloudfe
provisioner: kubernetes.io/aws-ebs
reclaimPolicy: Retain
parameters:
  type: io2
  iopsPerGB: "10"
  fsType: ext4